name: ✨ Feature Request
description: Suggest an idea for DwayBank
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! We appreciate your input.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Important for business needs
        - Critical - Blocking current usage
    validations:
      required: true

  - type: checkboxes
    id: components
    attributes:
      label: Affected Components
      description: Which parts of the system would this feature affect?
      options:
        - label: Authentication & Security
        - label: Database & Migrations
        - label: API Endpoints
        - label: User Interface
        - label: Smart Wallet Integration
        - label: KYC/Verification
        - label: Docker/Infrastructure
        - label: Testing & CI/CD

  - type: textarea
    id: requirements
    attributes:
      label: Acceptance Criteria
      description: What are the specific requirements for this feature?
      placeholder: |
        - [ ] Requirement 1
        - [ ] Requirement 2
        - [ ] Requirement 3

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here.