# DwayBank Grafana Datasource Configuration

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: "15s"
      queryTimeout: "60s"
      manageAlerts: true
      alertmanagerUid: "alertmanager"
      prometheusType: "Prometheus"
      prometheusVersion: "2.45.0"
      cacheLevel: "High"
      incrementalQuery: true
      incrementalQueryOverlapWindow: "10m"
      disableRecordingRules: false
      customQueryParameters: ""
      exemplarTraceIdDestinations:
        - name: "traceID"
          datasourceUid: "jaeger"
          urlDisplayLabel: "View trace"

  - name: Alertmanager
    type: alertmanager
    uid: "alertmanager"
    access: proxy
    url: http://alertmanager:9093
    editable: true
    jsonData:
      implementation: "prometheus"
      handleGrafanaManagedAlerts: true

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "dwaybank-logs-*"
    editable: true
    jsonData:
      interval: "Daily"
      timeField: "@timestamp"
      esVersion: "8.11.0"
      logMessageField: "message"
      logLevelField: "level"
      maxConcurrentShardRequests: 5
      includeFrozen: false

  - name: CloudWatch
    type: cloudwatch
    access: proxy
    editable: true
    jsonData:
      authType: "credentials"
      defaultRegion: "us-east-1"
      customMetricsNamespaces: "DwayBank,AWS/ApplicationELB,AWS/RDS,AWS/ElastiCache"
      assumeRoleArn: ""
    secureJsonData:
      accessKey: "${AWS_ACCESS_KEY_ID}"
      secretKey: "${AWS_SECRET_ACCESS_KEY}"