name: Automated Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Update npm dependencies
        run: |
          npx npm-check-updates -u
          npm install
          npm audit fix --force || true

      - name: Run tests with updated dependencies
        run: |
          npm run build
          npm run lint
          npm test

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: '🔄 Automated dependency updates'
          body: |
            ## Automated Dependency Updates
            
            This PR contains automated updates to project dependencies.
            
            ### Changes:
            - Updated npm packages to latest compatible versions
            - Applied automated security fixes
            - Verified tests pass with updated dependencies
            
            ### Review Checklist:
            - [ ] All tests pass
            - [ ] Security audit shows no high/critical issues  
            - [ ] Application starts successfully
            - [ ] No breaking changes in updated packages
            
            ---
            🤖 Generated automatically by GitHub Actions
          branch: automated-dependency-updates
          delete-branch: true

  security-updates:
    name: Security Updates
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Apply security updates
        run: |
          npm audit fix --force
          npm update

      - name: Verify application integrity
        run: |
          npm run build
          npm test

      - name: Create Security Update PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'security: apply automated security fixes'
          title: '🔒 Security vulnerability fixes'
          body: |
            ## Automated Security Updates
            
            This PR contains automated security vulnerability fixes.
            
            ### Security Fixes Applied:
            ```
            $(npm audit --audit-level=moderate)
            ```
            
            ### Verification:
            - [x] npm audit shows no high/critical vulnerabilities
            - [x] Application builds successfully
            - [x] Tests pass
            
            **⚠️ Priority: High** - Please review and merge promptly.
            
            ---
            🔒 Generated automatically by security monitoring
          branch: security-updates
          delete-branch: true
          labels: |
            security
            high-priority